# Request
bool take_off
float64 height
---
# Result
uint8 success
---
# Feedback
float64 current_height

# Standard values to put in the success field
uint8 SUCCESS = 0
uint8 NO_SYSTEM = 1
uint8 CONNECTION_ERROR = 2
uint8 BUSY = 3
uint8 COMMAND_DENIED = 4
uint8 COMMAND_DENIED_LANDED_STATE_UNKNOWN = 5
uint8 COMMAND_DENIED_NOT_LANDED = 6
uint8 TIMEOUT = 7
uint8 VTOL_TRANSITION_SUPPORT_UNKNOWN = 8
uint8 NO_VTOL_TRANSITION_SUPPORT = 9
uint8 PARAMETER_ERROR = 10
uint8 UNSUPPORTED = 11
uint8 FAILED = 12