/**:
  ros__parameters:
    drone:
      mass: 1.350 #Kg
      thrust_curve:
        # Formula T(N) = a * arctan(b * input + c) + d   
        # with input = [0.0, 100.0]
        identifier: 'Arctan'
        parameter_names: ["a", "b", "c", "d"]
        parameters: ["8.84", "2.955", "-1.478", "10.37"]