/**:
  ros__parameters:
    drone:
      mass: 1.350 #Kg
      thrust_curve:
        # Formula T(N) = a * arctan(b * input + c) + d
        # with input = [0.0, 1.0]
        type: 'arctan'
        a: 8.84
        b: 2.955
        c: -1.478
        d: 10.37