mavlink_interface:
  drivers:
    battery: "drivers/battery"
  state:
    arm: "state/arm"
    internal_state: "state/internal_state"
  sensors:
    imu: "sensors/imu"
    gps: "sensors/gps"
    filter: "nav/rel_state"
  