/**:
  ros__parameters:
    pid_node:
      rate: 10.0 # Hz
      topics:
        subscribers:
          state: "nav/state"
          path: "path"
        publishers:
          control: "control/attitude_force"
          statistics: "statistics/pid"
        services:
          mass: "thrust_curve"
      gains:
        # Gains for PIDs on [x, y, z]
        kp: [4.0, 4.0, 4.0]  # Proportional gain
        kd: [4.0, 4.0, 4.0]  # Derivative gain
        ki: [0.5, 0.5, 0.5]  # Integral gain
        kff: [1.0, 1.0, 1.0] # Feed-forward gain
        min_output: [-20.0, -20.0, -20.0] # Minimum output of each PID
        max_output: [20.0, 20.0, 2.0] # Maximum output of each PID