/**:
  ros__parameters:
    # Path/Trajectory representation setup
    path:
      sample_step: 0.0001
      topics:
        publishers:
          points: "path/points"
        subscribers:
          # Subscribe to the vehicle status and state
          status: "status"
          state: "nav/state"
        services:
          # Add/remove trajectories to/from the path
          reset: "path/reset"
          arc: "path/add_arc"
          line: "path/add_line"
          circle: "path/add_circle"
          lemniscate: "path/add_lemniscate"
          waypoint: "path/add_waypoint"
          # Start a mission to follow a given path or hold position
          start_mission: "path/start_mission"
          # Start a mission to land the vehicle
          land_mission: "path/land_mission"
          # ----------------------------------
          # Service clients for arming the vehicle and auto-landing
          arm: "arm"
          onboard_land: "land"
    # Controllers' gains and topic setup
    controllers:
      rate: 30.0 # Hz
      # PID controller topics and parameters
      pid:
        topics:
          subscribers:
            state: "nav/state"
          publishers:
            control: "control/attitude_force"
            statistics: "statistics/pid"
          services:
            mass: "thrust_curve"
        gains:
          # Gains for PIDs on [x, y, z]
          kp: [4.0, 4.0, 4.0]  # Proportional gain
          kd: [5.0, 5.0, 5.0]  # Derivative gain
          ki: [0.5, 0.5, 0.8]  # Integral gain
          kff: [1.0, 1.0, 1.0] # Feed-forward gain
          min_output: [-20.0, -20.0, -20.0] # Minimum output of each PID
          max_output: [20.0, 20.0, 20.0] # Maximum output of each PID
      # MPC controller topics and parameters
      mpc:
        topics:
          publishers:
            control: "control/attitude_rate_force"
        gains:
          T: 2.0  # The time window for the NMPC (in seconds)
          Q: [100.0, 100.0, 100.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0] # Diagonal matrix
          R: [0.1, 0.1, 0.1, 0.1]
          u_min: [ 1.0, -6.0, -6.0, -6.0] #[thrust_min, wx_min, wy_min, wz_min]
          u_max: [20.0,  6.0,  6.0,  6.0] #[thrust_max, wx_max, wy_max, wz_max]
      # Onboard controller topics and parameters
      onboard:
        topics:
          publishers:
            control: "control/position"
