/**:
  ros__parameters:
    subscribers:
      control:
        # High-level control (position, body velocity and inertial acceleration)
        position: "control/position"
        # Control the vehicle body velocity
        body_velocity: "control/body_velocity"
        # Low-level control (attitude and attitude-rate control + thrust)
        attitude_thrust: "control/attitude_thrust"
        attitude_rate_thrust: "control/attitude_rate_thrust"
        # Low-level control (attitude and attitude-rate control + force expresed in Newton)
        attitude_force: "control/attitude_force"
        attitude_rate_force: "control/attitude_rate_force"
      # External vision or mocap sensor input (in ENU frame of reference)
      external_sensors:
        mocap_enu: "mocap/pose_enu"
    services:
      arm: "arm"
      land: "land"
      reboot: "reboot"
      thrust_curve: "thrust_curve"
    publishers:
      # Current status of the vehicle (battery, operation mode, etc.)
      status: "status"
      # Sensor data received from micro-controller
      sensors:
        imu:
          vel_and_accel: "sensors/imu/vel_and_accel"
          magnetic_field: "sensors/imu/magnetic_field" 
      # Data received from the micro-controller internal EKF
      nav:
        # Current state of the vehicle
        state: "nav/state"