uint8 id                        # ID of the battery
float64 temperature             # Temperature of the battery in degrees Celsius
float64 voltage                 # Voltage of the battery in Volts
float64 percentage              # Remaining battery energy in percent        
float64 current                 # Current being drawn of the battery in Amps
float64 amps_hour_consumed      # Current consumed from the battery in Amps*hours