/**:
  ros__parameters:
    consensus:
      # Correspondences of the IDS on the adjacency matrix
      IDS: [1, 6, 8]
      # Communication edges of the graph (from->to, weight)
      edges: [[1,6], [6,8], [6,1]]
      weight: [1.0, 1.0]
      relative_positions: [[1.0, 1.0, 0.0], [-1.0, -1.0, 0.0], [1.0, 1.0, 0.0]]