---
uint8 success

# ---------------------------------
# Constants Definition for the result
# --------------------------------- 
uint8 UNKNOWN = 0
uint8 SUCCESS = 1
uint8 NO_SYSTEM = 2
uint8 CONNECTION_ERROR = 3
uint8 BUSY = 4
uint8 COMMAND_DENIED = 5
uint8 TIMEOUT = 6
uint8 NOSETPOINT_SET = 7
uint8 FAILED = 8